### create containers
POST http://localhost:8080/container/import
Content-Type: application/json

< json/containers.json

### get all containers
GET http://localhost:8080/container
Content-Type: application/json

### create tasks
POST http://localhost:8080/task/import
Content-Type: application/json

< json/tasks.json

### replace task
PATCH http://localhost:8080/task
Content-Type: application/json

{
  "taskId": "bd668f05-b57c-46f7-8df5-dc7fc2d38592",
  "taskOrder": 0,
  "container": {
    "containerId": "9cdf9b87-4ab3-43e7-9d7d-18efdd659fb6"
  }
}

### create todo
POST http://localhost:8080/task
Content-Type: application/json

{
  "taskName": "Task1",
  "destination": "Do some task1",
  "taskOrder": 1,
  "container": {
    "containerId": "88294900-bf0b-4297-99bc-d436a6acc7a1"
  }
}

### get all tasks
GET http://localhost:8080/task
Content-Type: application/json

